#!/bin/bash

CURDIR=`pwd`

# Parameters
STUDYNAMES=('G1' 'G2' 'G3' 'G4' 'G5')
STUDYSAMPLES=('2139' '2420' '2472' '2084' '3967')
#STUDYNAMES=('G1' 'G4')
#STUDYSAMPLES=('2139', '2084')
OLDIFS=$IFS; IFS="+"
NSAMPLE_TOT=`echo "${STUDYSAMPLES[*]}" | bc`
IFS=$OLDIFS

# data directories
DATADIR="/scratch/sbanerj/data/GerMIFS/imputed_QC_genotype"
GENO_FMT="${DATADIR}/[STUDY]/[STUDY]_QC_Chr[CHRM].imputed"
SAMPLE_FMT="${DATADIR}/[STUDY]/[STUDY]_QC.sample"
BASEDIR="/scratch/sbanerj/quasi_laplace_real"

# Pipeline directories
SCRIPTDIR="${CURDIR}/../scripts"
MASTER_BSUBDIR="${CURDIR}/../bsubfiles"
JOBSUBDIR="${CURDIR}/../jobsubs"
LDBASEDIR="${BASEDIR}/ldmap"
LDMAPWGHTDIR="${BASEDIR}/ldmap/weighted"
LDMAPCOMBDIR="${BASEDIR}/ldmap/combined"

# external programs required for the pipeline
SNPTEST="${HOME}/packages/SNPTEST/snptest_v2.5.4-beta3_linux_x86_64_dynamic/snptest_v2.5.4-beta3"
META="${HOME}/packages/META/meta"
LDSTORE="${HOME}/packages/ldstore/ldstore_v1.1_x86_64/ldstore"
BLORE="${HOME}/fine-mapping-SNPs/codebase/b-lore/bin/blore"
FINEMAP="${HOME}/packages/FINEMAP/finemap_v1.1_x86_64/finemap"

# other scripts used in the pipeline
GENINF="${SCRIPTDIR}/genomic_inflation_factor.py"
FILTERSNPS="${SCRIPTDIR}/filter_SNPS_hwe_nmeta.py"
DEFINELOCI="${SCRIPTDIR}/select_snps_from_meta.py"
CREATELOCI="${SCRIPTDIR}/create_loci.py"

# external files
KNOWNLOCI="${CURDIR}/../known_loci.txt"
